### ISSUE TITLE
No possibility for adding new bookmarks.

### ISSUE THREAD

**Issue by tomcat-xx** [SMFTricks/Reseller#1]
Hi, after switching to Reseller existing bookmarks are displayed but there seems to be no function for adding new ones. When clicking the + button for a topic you can add notification but no bookmark (if it should be behind the + button at all).

**Comment by DiegoAndresCortes** [comment]
What mod would that be?

**Comment by DiegoAndresCortes** [comment]
I'll close this one as it seems it's a mod issue
